### ISSUE TITLE
NAPRAWA DANYCH CORONAVIRUS

### ISSUE THREAD

**Issue by WerVa** [AmebyDevGroup/BlackMirror_Admin#22]
Po wybraniu Polski lub Globalnych trzeba zresetować lustro żeby zmiany się pobrały. 

PRIORYTET: PILNE

**Comment by chriswieczorek** [comment]
Po mojej stronie wszystko jest ok. Przy zmianie statusu działa poprawnie i wysyłam tylko jedną daną.
Temat u mnie zamykam i przenoszę do Clienta
